# Generated by Django 3.1.2 on 2020-10-25 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('collegename', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=56)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('courses', models.CharField(default='Masters', max_length=50)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('examname', models.CharField(max_length=30)),
                ('examscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fees', models.BigIntegerField()),
                ('fees_extra', models.BooleanField(default=False)),
                ('date_filled', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
