# Generated by Django 3.1.2 on 2020-10-17 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('collegename', models.TextField()),
                ('country', models.CharField(max_length=56)),
                ('university', models.CharField(default='Not Filled', max_length=60)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('examname', models.CharField(max_length=30)),
                ('examscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fees', models.BigIntegerField()),
            ],
        ),
    ]
