# Generated by Django 3.1.2 on 2020-11-10 06:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=56)),
            ],
            options={
                'verbose_name_plural': 'Countries',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('collegename', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=56)),
                ('university', models.CharField(blank=True, max_length=150)),
                ('courses', models.CharField(default='Masters', max_length=200)),
                ('cgpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('examname', models.CharField(max_length=30)),
                ('examscore', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fees', models.BigIntegerField()),
                ('fees_extra', models.BooleanField(default=False)),
                ('date_filled', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('university', models.CharField(blank=True, max_length=150, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRE_Website.country')),
            ],
            options={
                'verbose_name_plural': 'Universities',
            },
        ),
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(blank=True, max_length=200, null=True)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='GRE_Website.university')),
            ],
            options={
                'verbose_name_plural': 'Courses',
            },
        ),
    ]
