# Generated by Django 3.1.2 on 2020-11-10 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_Website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='university',
        ),
    ]
