# Generated by Django 3.1.2 on 2020-10-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='collegename',
            field=models.CharField(max_length=100),
        ),
    ]
