# Generated by Django 3.1.2 on 2020-10-19 20:53

from django.db import migrations, models
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_Website', '0002_auto_20201018_2357'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='date_filled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='student',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(max_length=60),
        ),
    ]
