# Generated by Django 3.1.2 on 2020-11-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_Website', '0002_remove_student_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
