# Generated by Django 3.1.2 on 2020-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_Website', '0003_auto_20201020_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='country',
            field=models.CharField(max_length=56),
        ),
    ]
