# Generated by Django 3.1.2 on 2020-10-20 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_Website', '0004_auto_20201020_0233'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.CharField(default='Not Filled', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='fees_extra',
            field=models.BooleanField(default=False),
        ),
    ]
