# Generated by Django 3.1.2 on 2020-10-20 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRE_Website', '0005_auto_20201020_2356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='courses',
            field=models.CharField(default='Masters', max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='university',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
